### ISSUE TITLE
How-to question

### ISSUE THREAD

**Issue by dollarspace** [dm-guy/utm-alternative#8]
Thank you for creating this solution. It looks like exactly what is needed, if we want to live without the __utmz cookie.

The question is, when do I start to see Source-Medium-Campaign accumulated in my new cookie? 

Example:
I visited my site directly and created a record utmz:(direct) in my new UTMZ Alternative cookie.
Then I visited the site via Google search (see original cookie content below) — but the cookie was not updated.

Here are these 2 cookies:
{ // __utmz original
    "domain": ".domain.com",
    "expirationDate": 1463734953,
    "hostOnly": false,
    "httpOnly": false,
    "name": "__utmz",
    "path": "/",
    "secure": false,
    "session": false,
    "value": "1xxxxxxx.14xxxxxx.2.2.utmcsr=google|utmgclid=xxxxxxxxxxxxx|utmccn=inline-branded|utmcmd=cpc|utmcct=proper",
},
{ // __utmz alternative
    "domain": ".domain.com",
    "expirationDate": 1510174328,
    "hostOnly": false,
    "httpOnly": false,
    "name": "altUTMZ",
    "path": "/",
    "secure": false,
    "session": false,
    "value": "utmz:(direct)",
}
Note how "value" is different.

I added your script via GTM.
Any help will be appreciated.
Thank you!

**Comment by dm-guy** [comment]
Hi, the cookie just take the campaign value of the UTMZ cookie (so, the utm_ccn value), it doesn't take the source and the medium. 
Would should have happened is that in the first load of the cookie, it should have put "inline-branded" in the value of the cookie. 

I do not know what it happened in your case. I need a bit more information - did you try it with a fresh browser without any cookies?

**Comment by dollarspace** [comment]
Thank you for the response.

Yes, I removed all cookies, then clicked a AdWords link in Google (with &utm_source=, etc). My UTMZ Alternative cookies keeps showing utmz:(direct).

**Comment by dm-guy** [comment]
OK. So you actually sending new traffic, with tags. In such case, utm-alternative will not take the utmz cookie. It will only take the utmz cookie if the utmz cookie already existed before utm-alternative script has ran. If you send new traffic from campaigns, then the plugin asks you to use the "src" parameter to add value to the cookie. 

However your use case can be implemented if you load analytics first, wait until the utmz is created, and only then run utm-alternative. GTM + Javascript will be handy in this case. 

But again, allow me to clarify that the logic of the plugin is that you are not depended on the UTMZ cookie anymore. Since classic analytics code will be deprecated in the future (no one said that officially, but that will be the case probably), UTMZ will be gone with it. Therefore the plugin encourages you to rely on your own parameters and your own cookie. I hope this makes sense!

**Comment by dollarspace** [comment]
I have no doubt that `__utmz` cookie will go the way of Google Wave. We are currently relying on it. I hope to use your script as a foundation for the replacement mechanism.

>> plugin asks you to use the "src" parameter

Aha. So if I want to change this line
       `var urlParamSRC = getURLParameter("src")`
to be
       `var urlParamSRC = getURLParameter("utm_source")`
?

Thank you.

**Comment by dm-guy** [comment]
I'm unable to test and review modifications that various users do to the code, but you can change the parameter as you like if it fits your needs.

**Comment by dm-guy** [comment]
Hi, pleased to share that the new release of the plugin supports the use case that you described. You are welcome to visit the plugin page for the new version.
